### ISSUE TITLE
Unicode error when searching for certain words like "loan", "loanword"

### ISSUE THREAD

**Issue by martino-vic** [lingpy/evobib#3]
It seems like the characters ö and ü in some works are triggering a Unicode error, see screenshot:

![image](https://user-images.githubusercontent.com/53435298/208142834-c408b342-b6c7-4cac-bb1f-4d1add99efcb.png)

On a somwhat unrelated note: While trying to reproduce this error with different words, I realised that searching for "as, if, for, from, id, or, author, title, home, editor, line, year, doi, url, ..." gives a <type 'exceptions.AttributeError'>, not sure if that's relevant, but thought it's worth mentioning.

**Comment by LinguList** [comment]
The error is fixed now, thanks for pointing this out!

**Comment by martino-vic** [comment]
Yes, works perfectly! No worries, happy that bug reporting is appreciated :) Thx for fixing.
